### ISSUE TITLE
[Asked] What happens if there’re two predictive saccades?

### ISSUE THREAD

**Issue by LorenzoRampersad** [vrijeuniversiteit/vrgaze#3]
We asked David this question, and he said in case this happens we should use the last one. Is it possible for you to output only that one in the output file? Else we will do it manually, that’s also not a problem.

**Comment by footballdaniel** [comment]
Hey, i have changed it. right now each row of the results contains information about the current ball/trial.

If there is no predictive saccade, the flag "isValid" is "False" because the trial cant be analyzed. Also, the row will look mostly empty, because there are no predictive saccades found.

In case there is one predictive saccade, it is visible in the file.

In case there are two predictive saccades, **only the last one** will be exported.

The newest version (1.3.20, i think) should have all of these changes, so feel free to upgrade your package!

(also, if you find any potential errors in the data, lmk. The pipeline has only been tested with a  few trials)
